feat: added <PrismicRichText />
prismicio/prismic-reactjs pull request #96
Opened 2021-07-19 20:08 UTC by dayhaysoos

- Added <PrismicRichText /> 
- Wrote tests for <PrismicRichText />

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

PrismicRichText is an essential tool for using Prismic. This PR is a React version of that implementation.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x ] All new and existing tests are passing.

![babyducks](https://user-images.githubusercontent.com/1852675/126220695-200a98c7-dd92-46ae-8a86-20d2b893395e.jpeg)

2021-07-21 00:29 UTC, angeloashmore requested changes
Looking good! Most of my comments are stylistic or naming changes. Everything looks good from a functional standpoint. 👍

2021-07-21 00:29 UTC, angeloashmore commented on src/PrismicRichText.tsx
> +// const escapeHtml = require("escape-html");
We can remove escapeHtml since we aren't using it.

2021-07-21 00:29 UTC, angeloashmore commented on src/PrismicRichText.tsx
> +import { LinkResolverFunction } from "@prismicio/helpers";
We can use `prismicH.LinkResolverFunction` since we already imported it as a namespace on the next line.

2021-07-21 00:29 UTC, angeloashmore commented on src/PrismicRichText.tsx
> +// const { Elements } = PrismicRichText;
Can remove temporary comments like this.

2021-07-21 00:29 UTC, angeloashmore commented on src/PrismicRichText.tsx
> +};
Similar to the `@prismicio/types` library documentation effort, we'll want to document all types, functions, and constants. `@prismicio/client`'s v6 branch contains a thorough example (https://github.com/prismicio/prismic-javascript/blob/aa/v6/src/client.ts).

2021-07-21 00:29 UTC, angeloashmore commented on src/types.ts
> +export type ComponentMapSerializer = RichTextMapSerializer<React.ReactNode>;
Since we're using `JSX.Element` as the return type in the default serializer, we can change our types here to reflect the same.

```ts
export type JSXFunctionSerializer = RichTextFunctionSerializer<JSX.Element>;
export type JSXMapSerializer = RichTextMapSerializer<JSX.Element>;
```

We should also update the type description to convey that the result will be a JSX Element. It currently says it will serialize a Rich Text field to HTML which is incorrect.

2021-07-21 00:29 UTC, angeloashmore commented on src/PrismicRichText.tsx
> +			return <h1>{children}</h1>;
This is purely stylistic, but could we have empty lines between each case?

E.g.:

```ts
case Element.heading1:
  return <h1>{children}</h1>

case Element.heading2:
  return <h3>{children}</h2>

case Element.heading3:
  return <h3>{children}</h3>
```

2021-07-21 00:29 UTC, angeloashmore commented on src/PrismicRichText.tsx
> +			// TODO: Make sure label wasn't needed here
We'll need to test this TODO. We can test it in the Writing Room by creating a preformatted block and add a label to it. We can run the result through the serializer and see if it gets wrapped in a `<span className="label-name">`. If it doesn't, we'll need to add the label here.

If it does wrap in a `<span>`, we need to consider the HTML semantics of that. Is `<pre>` a valid child of `<span>`?

2021-07-21 00:29 UTC, angeloashmore commented on src/PrismicRichText.tsx
> +			return <>{content}</>;
I found an example of how we could convert `\n` to `<br />` in React. This idea is taken from the current `prismic-reactjs` default serializer.

This is untested and possibly could be done better without a `forEach` loop and `push`, but the concept is sound.

```ts
// For each new line (`\n`) in the content, replace it with a <br />
const result = []

content.split('\n').forEach((line, index) => {
  if (index > 0) {
    result.push(<br />)
  }

  result.push(line)
})
```

2021-07-21 00:29 UTC, angeloashmore commented on src/PrismicRichText.tsx
> +	const val = serialize(props.field, serializer);
This should be wrapped in a `React.useMemo` hook for better efficiency.

2021-07-21 00:29 UTC, angeloashmore commented on src/PrismicRichText.tsx
> +	const components = props.components || context.richTextComponents;
I don't remember why this was marked as a TODO, but I think we can leave this without a `React.useMemo`.

2021-07-21 00:29 UTC, angeloashmore commented on test/PrismicRichText.test.tsx
> +			text: "Heading 1 bold text italic still bold normal",
The "Heading 1 bold text italic still bold normal" that this fixture was taken from included spans for "bold", "italic".

Since this is a simple `<h1>` test, we can remove some noise by changing the text to "Heading 1" or something.

(Same goes for the other heading tests)

2021-07-21 00:29 UTC, angeloashmore commented on test/PrismicRichText.test.tsx
> +test("returns <p /> JSX if type is paragraph", (t) => {
The test names are stylistically inconsistent. The following format seems to work well:

```
returns <p> if type is paragraph
returns <h1> if type is heading1
returns <$0> if type is $1
```

2021-07-21 00:29 UTC, angeloashmore commented on test/PrismicRichText.test.tsx
> +// TODO update isInternalURL to support an internal URL like "url"
I think we can remove this TODO and convert it to a GitHub issue to track it better.

2021-07-21 00:29 UTC, angeloashmore commented on test/PrismicRichText.test.tsx
> +			<a data-href={"/url"} data-rel={undefined} data-target={undefined}>
Style: prefer `data-href="/url"` over `data-href={"/url"}`

2021-07-21 00:29 UTC, angeloashmore commented on test/PrismicRichText.test.tsx
> +	t.deepEqual(actual, expected);
Style: Consistently add an empty space before test assertions (e.g. `t.deepEqual`) or not. In some previous tests, there was no space.

2021-07-26 15:18 UTC, dayhaysoos commented on src/PrismicRichText.tsx
> +};
Would like feedback on the comments I've made

2021-07-27 02:50 UTC, angeloashmore commented on src/PrismicRichText.tsx
> +};
I think we could be more descriptive in the comments. The goal is to give users a good understanding of what is being described, only falling back to the Prismic docs when it cannot be done in a reasonable amount of space.

For the PrismicRichText component, we could do something like this:

```ts
/**
 * React component that renders content from a Prismic Rich Text field. By default, HTML elements are rendered for each piece of content. A `heading1` block will render an `<h1>` HTML element, for example. Links will use `<PrismicLink>` by default which can be customized using the `internalLinkComponent` and `externalLinkComponent` props.
 *
 * To customize the components that are rendered, provide a map or function serializer to the `components` prop.
 *
 * Components can also be provided in a centralized location using the `<PrismicProvider>` React context provider.
 *
 * @remarks This component returns a React fragment with no wrapping element around the content. If you need a wrapper, add a component around `<PrismicRichText>`.
 *
 * @see Learn about Rich Text fields {@link https://prismic.io/docs/core-concepts/rich-text-title}
 * @see Learn about Rich Text serializers {@link https://prismic.io/docs/core-concepts/html-serializer}
 *
 * @example
 * Rendering a Rich Text field using the default HTMl elements.
 *
 * <PrismicRichText field={document.data.content} />
 *
 * @example
 * Rendering a Rich Text field using a custom set of React components.
 *
 * <PrismicRichText
 *   field={document.data.content}
 *   components={{
 *		 heading1: ({ children }) => <Heading>{children}</Heading>
 *   }}
 * />
 *
 * @param props Props for the component.
 *
 * @returns The Rich Text field's content as React components.
 */
const PrismicRichText = (props: PrismicRichTextProps): JSX.Element => {
  /* ... */
}
```

The primary user-facing APIs will need this level of documentation within the library. The types used within these APIs, such as `PrismicRichTextProps`, can be less verbose. One sentence per prop is enough unless there is a need to be more descriptive.

```ts
/**
 * Props for `<PrismicRichText>`.
 */
export type PrismicRichTextProps = {
	/** The Prismic Rich Text field to render. */
	field: prismicT.RichTextField;
	/**
	 * The Link Resolver used to resolve links.
	 *
	 * @remarks If your app uses Route Resolvers when querying for your Prismic repository's content, a Link Resolver does not need to be provided.
	 *
	 * @see Learn about Link Resolvers and Route Resolvers {@link https://prismic.io/docs/core-concepts/link-resolver-route-resolver}
	 */
	linkResolver?: PrismicLinkProps["linkResolver"];
	/**
	 * A function that maps a Rich Text block to a React component.
	 *
	 * @see Learn about Rich Text serializers {@link https://prismic.io/docs/core-concepts/html-serializer}
	 *
	 * @deprecated Use the `components` prop instead. Prefer using a map serializer when possible.
	 * */
	htmlSerializer?: RichTextFunctionSerializer<React.ComponentType>;
	/**
	 * A map or function that maps a Rich Text block to a React component.
	 *
	 * @remarks Prefer using a map serializer over the function serializer when possible. The map serializer is simpler to maintain.
	 *
	 * @example
	 * A map serializer.
	 *
	 * ```ts
	 * {
	 *   heading1: ({children}) => <Heading>{children}</Heading>
	 * }
	 * ```
	 *
	 * @example
	 * A function serializer.
	 *
	 * ```ts
	 * (type, node, content, children) => {
	 *	 switch (type) {
	 *	   case 'heading1': {
	 *	     return <Heading>{chidlren}</Heading>
	 *	   }
	 *	 }
	 * }
	 * ```
	 */
	components?:
		| RichTextMapSerializer<JSX.Element>
		| RichTextFunctionSerializer<JSX.Element>;
	/**
	 * The React component rendered for links when the URL is internal.
	 *
	 * @default `<a>`
	 */
	internalLinkComponent?: PrismicLinkProps["internalComponent"];
	/**
	 * The React component rendered for links when the URL is external.
	 *
	 * @default `<a>`
	 */
	externalLinkComponent?: PrismicLinkProps["externalComponent"];
};
```

2021-07-27 02:51 UTC, angeloashmore commented on src/PrismicRichText.tsx
> +	htmlSerializer?: RichTextFunctionSerializer<React.ComponentType>;
I think this is supposed to be `RichTextFunctionSerializer<JSX.Element>`

2021-07-27 02:52 UTC, angeloashmore commented
The updates are looking good! I added a comment above about the in-code documentation with a lengthy example.

2021-07-27 10:25 UTC, dayhaysoos commented on src/PrismicRichText.tsx
> +};
Noted for next time, thank you. For now I'm going to copy/pasta what you have here lol

2021-07-27 10:41 UTC, dayhaysoos commented
Question: Does the defaultComponentSerializer need to have comments on it, since it's not really something users would be calling directly?

2021-07-27 21:54 UTC, angeloashmore commented
> Question: Does the defaultComponentSerializer need to have comments on it, since it's not really something users would be calling directly?

It doesn't need to be deeply documented since it is an internal function. It would still be good to document what it's doing for future developers to understand its purpose.

Personally, I would just add a sentence or two describing what it's doing (using default HTML elements for block types) and what it's for (the fallback serializer if one is not provided).

2021-07-29 01:28 UTC, merged